import SLIDE1 from "../assets/images/slide1.jpg";
import SLIDE2 from "../assets/images/slide2.jpg";
import SLIDE3 from "../assets/images/slide3.jpg";
import DELIVER from "../assets/images/deliver.png";
import VEGETABLE from "../assets/images/vegetables.png";
import BADGE from "../assets/images/badge.png";
import SUPPORT from "../assets/images/support.png";
import CATEGORY from "../assets/images/category.jpg";
import CATEGORY_1 from "../assets/images/category-1.jpg";
import CATEGORY_2 from "../assets/images/category-2.jpg";
import CATEGORY_3 from "../assets/images/category-3.jpg";
import CATEGORY_4 from "../assets/images/category-4.jpg";
export { SLIDE1, SLIDE2, SLIDE3, DELIVER,VEGETABLE, BADGE,SUPPORT, CATEGORY,CATEGORY_1,CATEGORY_2,CATEGORY_3,CATEGORY_4 };
